defmodule Portal.Repo.Migrations.AddMfaResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:portal_passkeys, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:credential_id, :binary, null: false)
      add(:public_key, :binary, null: false)
      add(:sign_count, :bigint, null: false, default: 0)
      add(:aaguid, :binary)
      add(:transports, {:array, :text})
      add(:nickname, :text, null: false)
      add(:last_used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:portal_users,
          column: :id,
          name: "portal_passkeys_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:portal_passkeys, [:credential_id],
        name: "portal_passkeys_unique_credential_id_index"
      )
    )

    create(index(:portal_passkeys, [:user_id]))

    create table(:portal_recovery_codes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:code_hash, :text, null: false)
      add(:used_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:portal_users,
          column: :id,
          name: "portal_recovery_codes_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(index(:portal_recovery_codes, [:user_id]))

    create(index(:portal_recovery_codes, [:code_hash]))

    create table(:portal_totp_secrets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:secret, :binary, null: false)
      add(:confirmed_at, :utc_datetime_usec)
      add(:last_used_at, :utc_datetime_usec)
      add(:failed_attempts, :bigint, null: false, default: 0)
      add(:locked_until, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:portal_users,
          column: :id,
          name: "portal_totp_secrets_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:portal_totp_secrets, [:user_id],
        name: "portal_totp_secrets_unique_user_index"
      )
    )
  end

  def down do
    drop(constraint(:portal_totp_secrets, "portal_totp_secrets_user_id_fkey"))

    drop_if_exists(
      unique_index(:portal_totp_secrets, [:user_id],
        name: "portal_totp_secrets_unique_user_index"
      )
    )

    drop(table(:portal_totp_secrets))

    drop_if_exists(index(:portal_recovery_codes, [:code_hash]))

    drop_if_exists(index(:portal_recovery_codes, [:user_id]))

    drop(constraint(:portal_recovery_codes, "portal_recovery_codes_user_id_fkey"))

    drop(table(:portal_recovery_codes))

    drop_if_exists(index(:portal_passkeys, [:user_id]))

    drop(constraint(:portal_passkeys, "portal_passkeys_user_id_fkey"))

    drop_if_exists(
      unique_index(:portal_passkeys, [:credential_id],
        name: "portal_passkeys_unique_credential_id_index"
      )
    )

    drop(table(:portal_passkeys))
  end
end
