defmodule Portal.Repo.Migrations.InitialPostgres do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:portal_users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:username, :text, null: false)
      add(:hex_username, :text)
      add(:hex_profile, :text, default: "{}")
      add(:github_username, :text)
      add(:github_profile, :text, default: "{}")
      add(:password_hash, :text, null: false)
      add(:is_admin, :boolean, null: false, default: false)
      add(:last_hex_login_at, :utc_datetime)
      add(:last_github_login_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:portal_users, [:github_username]))

    create(index(:portal_users, [:hex_username]))

    create(index(:portal_users, [:username], unique: true))

    create table(:portal_scan_requests, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:package_name, :text, null: false)
      add(:version, :text)
      add(:source, :text, null: false)
      add(:status, :text, null: false, default: "accepted")
      add(:user_id, :uuid)
      add(:subject, :text)
      add(:verification_provider, :text)
      add(:error_reason, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:portal_scan_requests, [:source]))

    create(index(:portal_scan_requests, [:status]))

    create(
      index(:portal_scan_requests, [:package_name, :status],
        name: "portal_scan_requests_package_status_index"
      )
    )

    create table(:catalog_system_results, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:system_pkg, :text, null: false)
      add(:system_version, :text)
      add(:status, :text, null: false)
      add(:firmware_size_bytes, :bigint)
      add(:hex_version_tested, :text)
      add(:beam_scan, :map)
      add(:dependency_scans, :map)
      add(:log_path, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:run_id, :uuid, null: false)
    end

    create(index(:catalog_system_results, [:system_pkg, :status]))

    create(index(:catalog_system_results, [:run_id]))

    create table(:catalog_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:catalog_system_results) do
      modify(
        :run_id,
        references(:catalog_runs,
          column: :id,
          name: "catalog_system_results_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:catalog_runs) do
      add(:run_id, :text, null: false)
      add(:version_tested, :text, null: false)
      add(:image_digest, :text)
      add(:overall_status, :text)
      add(:footprint, :map)
      add(:log, :text)
      add(:started_at, :utc_datetime_usec)
      add(:finished_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:package_id, :uuid, null: false)
      add(:scan_request_id, :uuid)
    end

    create(index(:catalog_runs, [:finished_at]))

    create(index(:catalog_runs, [:scan_request_id]))

    create(index(:catalog_runs, [:package_id]))

    create(unique_index(:catalog_runs, [:run_id], name: "catalog_runs_unique_run_id_index"))

    create table(:catalog_packages, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:catalog_runs) do
      modify(
        :package_id,
        references(:catalog_packages,
          column: :id,
          name: "catalog_runs_package_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :scan_request_id,
        references(:portal_scan_requests,
          column: :id,
          name: "catalog_runs_scan_request_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:catalog_packages) do
      add(:name, :text, null: false)
      add(:description, :text)
      add(:latest_version, :text)
      add(:last_run_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(index(:catalog_packages, [:name], unique: true))

    create(unique_index(:catalog_packages, [:name], name: "catalog_packages_unique_name_index"))

    create table(:catalog_package_overrides, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:package_name, :text, null: false)
      add(:forced_status, :text)
      add(:allow_systems, {:array, :text}, default: [])
      add(:deny_systems, {:array, :text}, default: [])
      add(:notes, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:catalog_package_overrides, [:package_name],
        name: "catalog_package_overrides_unique_package_name_index"
      )
    )

    create table(:catalog_artifacts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:sha256, :text, null: false)
      add(:byte_size, :bigint)
      add(:disk_path, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :system_result_id,
        references(:catalog_system_results,
          column: :id,
          name: "catalog_artifacts_system_result_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(index(:catalog_artifacts, [:system_result_id]))

    create(
      unique_index(:catalog_artifacts, [:sha256], name: "catalog_artifacts_unique_sha256_index")
    )
  end

  def down do
    drop(constraint(:catalog_artifacts, "catalog_artifacts_system_result_id_fkey"))

    drop_if_exists(
      unique_index(:catalog_artifacts, [:sha256], name: "catalog_artifacts_unique_sha256_index")
    )

    drop_if_exists(index(:catalog_artifacts, [:system_result_id]))

    drop(table(:catalog_artifacts))

    drop_if_exists(
      unique_index(:catalog_package_overrides, [:package_name],
        name: "catalog_package_overrides_unique_package_name_index"
      )
    )

    drop(table(:catalog_package_overrides))

    drop_if_exists(
      unique_index(:catalog_packages, [:name], name: "catalog_packages_unique_name_index")
    )

    drop_if_exists(index(:catalog_packages, [:name]))

    alter table(:catalog_packages) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:last_run_at)
      remove(:latest_version)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:catalog_runs, "catalog_runs_package_id_fkey"))

    drop(constraint(:catalog_runs, "catalog_runs_scan_request_id_fkey"))

    alter table(:catalog_runs) do
      modify(:scan_request_id, :uuid)
      modify(:package_id, :uuid)
    end

    drop(table(:catalog_packages))

    drop_if_exists(
      unique_index(:catalog_runs, [:run_id], name: "catalog_runs_unique_run_id_index")
    )

    drop_if_exists(index(:catalog_runs, [:package_id]))

    drop_if_exists(index(:catalog_runs, [:scan_request_id]))

    drop_if_exists(index(:catalog_runs, [:finished_at]))

    alter table(:catalog_runs) do
      remove(:scan_request_id)
      remove(:package_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:finished_at)
      remove(:started_at)
      remove(:log)
      remove(:footprint)
      remove(:overall_status)
      remove(:image_digest)
      remove(:version_tested)
      remove(:run_id)
    end

    drop(constraint(:catalog_system_results, "catalog_system_results_run_id_fkey"))

    alter table(:catalog_system_results) do
      modify(:run_id, :uuid)
    end

    drop(table(:catalog_runs))

    drop_if_exists(index(:catalog_system_results, [:run_id]))

    drop_if_exists(index(:catalog_system_results, [:system_pkg, :status]))

    drop(table(:catalog_system_results))

    drop_if_exists(
      index(:portal_scan_requests, [:package_name, :status],
        name: "portal_scan_requests_package_status_index"
      )
    )

    drop_if_exists(index(:portal_scan_requests, [:status]))

    drop_if_exists(index(:portal_scan_requests, [:source]))

    drop(table(:portal_scan_requests))

    drop_if_exists(index(:portal_users, [:username]))

    drop_if_exists(index(:portal_users, [:hex_username]))

    drop_if_exists(index(:portal_users, [:github_username]))

    drop(table(:portal_users))
  end
end
