defmodule Portal.Repo.Migrations.AddLinkedLogins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:portal_users) do
      add(:github_id, :bigint)
      add(:password_set, :boolean, null: false, default: true)
    end

    # Every GitHub link made so far stored the /user body, which carries the id.
    execute("""
    UPDATE portal_users
       SET github_id = (github_profile::jsonb ->> 'id')::bigint
     WHERE github_id IS NULL
       AND github_username IS NOT NULL
       AND jsonb_typeof(github_profile::jsonb -> 'id') = 'number'
    """)

    # Accounts a provider flow created have a random password nobody knows.
    # Registered accounts that a provider flow later linked keep `true`; the
    # rows this flips are checked by hand before release (see the plan).
    execute("""
    UPDATE portal_users
       SET password_set = false
     WHERE (hex_username IS NOT NULL AND lower(username) = lower(hex_username) AND last_hex_login_at IS NOT NULL)
        OR (github_username IS NOT NULL AND lower(username) = lower(github_username) AND last_github_login_at IS NOT NULL)
    """)

    drop_if_exists(index(:portal_users, [:hex_username]))

    create(index(:portal_users, [:hex_username], unique: true, where: "hex_username IS NOT NULL"))

    create(index(:portal_users, [:github_id], unique: true, where: "github_id IS NOT NULL"))
  end

  def down do
    drop_if_exists(index(:portal_users, [:github_id]))

    drop_if_exists(index(:portal_users, [:hex_username]))

    create(index(:portal_users, [:hex_username]))

    alter table(:portal_users) do
      remove(:password_set)
      remove(:github_id)
    end
  end
end
