defmodule Portal.Repo.Migrations.AddPasswordResetRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:portal_users) do
      add(:password_reset_required, :boolean, null: false, default: false)
    end
  end

  def down do
    alter table(:portal_users) do
      remove(:password_reset_required)
    end
  end
end
