defmodule Portal.Repo.Migrations.AddSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:settings, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false, default: "global")
      add(:argus_enabled, :boolean, null: false, default: true)
      add(:argus_analyses, {:array, :text}, null: false)
      add(:argus_scope, :text, null: false, default: "firmware")
      add(:argus_min_severity, :text, null: false, default: "warning")
      add(:argus_timeout_seconds, :bigint, null: false, default: 300)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:settings, [:key], name: "settings_unique_key_index"))
  end

  def down do
    drop_if_exists(unique_index(:settings, [:key], name: "settings_unique_key_index"))

    drop(table(:settings))
  end
end
