defmodule Portal.Repo.Migrations.CatalogBrowseIndexes do
  @moduledoc """
  Indexes for reading `/packages` a page at a time from Postgres
  (`Portal.Catalog.Browse`) and for counting `stats_json/0` from an index, and
  the removal of three indexes they make redundant: a duplicate unique index on
  `catalog_packages.name`, `catalog_runs (package_id)` (a strict prefix of the
  new latest-run index) and `catalog_system_results (system_pkg, status)`
  (replaced by the stats index, and used by no query).

  Generated by `mix ash_postgres.generate_migrations`; the `pg_trgm` extension
  is added by hand, because the trigram indexes need it and Ash only manages
  extensions through a separate migration of its own.

  Plain `CREATE INDEX`, not `CONCURRENTLY`: on 2026-10-06 the largest of these
  tables held ~42k rows, so the write lock lasts well under a second, and a
  concurrent build cannot run inside the migration's transaction.
  """

  use Ecto.Migration

  def up do
    # The drops need an exclusive lock on tables the site reads constantly. A
    # long-running reader would leave them queued behind it, and every request
    # queued behind them: fail the deploy after 5s instead of stalling the site.
    execute("SET LOCAL lock_timeout = '5s'")

    # The `portal` role owns the database on production, and `pg_trgm` is a
    # trusted extension there, so this needs no superuser.
    execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    create(
      index(:catalog_packages, ["name gin_trgm_ops"],
        name: "catalog_packages_name_trgm_index",
        using: "gin"
      )
    )

    # `catalog_packages_name_index`, a byte-for-byte copy of the `:unique_name`
    # identity's `catalog_packages_unique_name_index`.
    drop_if_exists(index(:catalog_packages, [:name]))

    create(
      index(:catalog_runs, [:package_id, desc: :finished_at, desc: :inserted_at],
        name: "catalog_runs_package_latest_index"
      )
    )

    create(
      index(:portal_scan_requests, ["package_name gin_trgm_ops"],
        name: "portal_scan_requests_package_name_trgm_index",
        using: "gin"
      )
    )

    drop_if_exists(index(:catalog_runs, [:package_id]))

    create(
      index(:catalog_system_results, [:system_pkg, :system_version, :status],
        name: "catalog_system_results_stats_index"
      )
    )

    drop_if_exists(index(:catalog_system_results, [:system_pkg, :status]))
  end

  def down do
    create(index(:catalog_system_results, [:system_pkg, :status]))

    drop_if_exists(
      index(:catalog_system_results, [:system_pkg, :system_version, :status],
        name: "catalog_system_results_stats_index"
      )
    )

    create(index(:catalog_runs, [:package_id]))

    drop_if_exists(
      index(:portal_scan_requests, ["package_name gin_trgm_ops"],
        name: "portal_scan_requests_package_name_trgm_index"
      )
    )

    drop_if_exists(
      index(:catalog_runs, [:package_id, desc: :finished_at, desc: :inserted_at],
        name: "catalog_runs_package_latest_index"
      )
    )

    create(index(:catalog_packages, [:name], unique: true))

    drop_if_exists(
      index(:catalog_packages, ["name gin_trgm_ops"], name: "catalog_packages_name_trgm_index")
    )

    execute("DROP EXTENSION IF EXISTS pg_trgm")
  end
end
