defmodule Portal.Repo.Migrations.AddScanRequestErrorLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:portal_scan_requests) do
      add(:error_log, :text)
    end
  end

  def down do
    alter table(:portal_scan_requests) do
      remove(:error_log)
    end
  end
end
