defmodule Portal.Repo.Migrations.AddDashboardFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_system_results) do
      add(:log_tail, :text)
      add(:failure_category, :text)
    end

    alter table(:catalog_packages) do
      add(:native_components, :map)
    end
  end

  def down do
    alter table(:catalog_packages) do
      remove(:native_components)
    end

    alter table(:catalog_system_results) do
      remove(:failure_category)
      remove(:log_tail)
    end
  end
end
