defmodule Portal.Repo.Migrations.Phase3ScanRequestRunLink do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:portal_scan_requests) do
      add(:run_id, :uuid)
    end
  end

  def down do
    alter table(:portal_scan_requests) do
      remove(:run_id)
    end
  end
end
