defmodule Portal.Repo.Migrations.AddPackageHexMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_packages) do
      add(:hex_links, :map)
      add(:hex_owners, {:array, :text})
      add(:hex_meta_fetched_at, :utc_datetime)
    end
  end

  def down do
    alter table(:catalog_packages) do
      remove(:hex_meta_fetched_at)
      remove(:hex_owners)
      remove(:hex_links)
    end
  end
end
