defmodule Portal.Repo.Migrations.AddRunArgus do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:catalog_runs) do
      add(:argus, :map)
    end
  end

  def down do
    alter table(:catalog_runs) do
      remove(:argus)
    end
  end
end
