defmodule Portal.Repo.Migrations.AddFindingTriage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_finding_triage, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:fingerprint, :text, null: false)
      add(:package_name, :text, null: false)
      add(:analysis, :text, null: false)
      add(:severity, :text, null: false)
      add(:title, :text, null: false)
      add(:file, :text)
      add(:line, :bigint)
      add(:finding, :map)
      add(:status, :text, null: false, default: "new")
      add(:note, :text)
      add(:first_seen_version, :text)
      add(:last_seen_version, :text)
      add(:last_seen_run_id, :uuid)
      add(:updated_by, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:catalog_finding_triage, [:fingerprint],
        name: "catalog_finding_triage_unique_fingerprint_index"
      )
    )

    create(index(:catalog_finding_triage, [:status]))

    create(index(:catalog_finding_triage, [:package_name]))
  end

  def down do
    drop_if_exists(index(:catalog_finding_triage, [:package_name]))

    drop_if_exists(index(:catalog_finding_triage, [:status]))

    drop_if_exists(
      unique_index(:catalog_finding_triage, [:fingerprint],
        name: "catalog_finding_triage_unique_fingerprint_index"
      )
    )

    drop(table(:catalog_finding_triage))
  end
end
