defmodule Portal.Repo.Migrations.AddSystemLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:catalog_system_logs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:body, :text, null: false)
      add(:byte_size, :bigint)
      add(:truncated, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :system_result_id,
        references(:catalog_system_results,
          column: :id,
          name: "catalog_system_logs_system_result_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(
      unique_index(:catalog_system_logs, [:system_result_id],
        name: "catalog_system_logs_unique_system_result_index"
      )
    )
  end

  def down do
    drop(constraint(:catalog_system_logs, "catalog_system_logs_system_result_id_fkey"))

    drop_if_exists(
      unique_index(:catalog_system_logs, [:system_result_id],
        name: "catalog_system_logs_unique_system_result_index"
      )
    )

    drop(table(:catalog_system_logs))
  end
end
