defmodule PortalWeb.SecurityController do
  @moduledoc """
  Enrolment and removal of second factors.

  Viewing the page is free; changing anything needs a re-authentication inside
  the last ten minutes, with a credential `Portal.Accounts.Mfa` accepts for
  this account. The password counts only while the account holds no factor —
  otherwise a phished password would let an attacker enrol their own passkey,
  which is exactly what the admin passkey requirement exists to prevent.

  ## Recovery codes are generated by a click, not by enrolment

  The spec has recovery codes minted on first successful factor enrolment.
  Here a banner appears the moment a first factor lands and the person presses
  a button. The reason is narrow: the plaintext must reach exactly one rendered
  response and must never sit in the session, and Phoenix's cookie store is
  signed rather than encrypted. Handing the codes back through the JSON
  response to passkey registration, or stashing them across a redirect, both
  put the plaintext somewhere it does not belong. One button, rendered
  directly, has neither problem.
  """

  use PortalWeb, :controller

  require Logger

  alias Portal.Accounts.{Mfa, Passkeys, RecoveryCodes, Totp, WebAuthn}
  alias PortalWeb.{UserAuth, WebAuthnSession}

  # Two keys, side by side: enrolling a passkey and proving one you already
  # hold are separate ceremonies and can be in flight at the same time.
  @registration_key :passkey_registration_challenge
  @reauth_key :passkey_reauth_challenge

  @json_actions [:registration_challenge, :create_passkey, :reauth_challenge, :reauth_passkey]

  @guarded_actions [
    :registration_challenge,
    :create_passkey,
    :delete_passkey,
    :start_totp,
    :confirm_totp,
    :delete_totp,
    :regenerate_recovery_codes
  ]

  # `:show` and `:reauth` are deliberately absent: you must be able to read the
  # page, and to start a re-authentication, without already holding one.
  plug :require_fresh_reauth when action in @guarded_actions

  # One message for every passkey failure. Telling "no such credential" apart
  # from "bad signature" would confirm which credential ids are real.
  @passkey_denied "That passkey could not be verified."

  def show(conn, _params), do: render_page(conn)

  # --- Re-authentication -----------------------------------------------------

  def reauth(conn, %{"method" => method, "credential" => credential}) do
    user = conn.assigns.current_user
    method = parse_method(method)

    cond do
      method not in Mfa.accepted_reauth_methods(user) ->
        render_page(conn, error: reauth_message(user))

      proven?(user, method, credential) ->
        conn
        |> UserAuth.mark_reauth(method)
        |> put_flash(:info, "Confirmed. You have #{window_minutes()} minutes to make changes.")
        |> redirect(to: ~p"/settings/security")

      true ->
        render_page(conn, error: "That did not match. Try again.")
    end
  end

  def reauth(conn, _params) do
    render_page(conn, error: reauth_message(conn.assigns.current_user))
  end

  def reauth_challenge(conn, _params) do
    {challenge, payload} = WebAuthn.authentication_challenge()

    conn
    |> WebAuthnSession.put(@reauth_key, challenge)
    |> json(payload)
  end

  def reauth_passkey(conn, params) do
    # `case` rather than `with`: the conn returned by `take/2` is the one that
    # has the challenge cleared out of the session, and a `with` else-clause
    # cannot see a variable bound inside the chain — it would answer on the
    # stale conn and leave a spent key behind.
    case WebAuthnSession.take(conn, @reauth_key) do
      {:ok, challenge, conn} -> verify_reauth(conn, params, challenge)
      {:error, conn} -> json_error(conn, :unauthorized, @passkey_denied)
    end
  end

  defp verify_reauth(conn, params, challenge) do
    # A discoverable credential names its own owner, so the assertion that
    # comes back need not belong to the session making the request. Pinning
    # the signed-in id is what stops an attacker re-authorising your session
    # with a passkey of their own.
    user_id = conn.assigns.current_user.id

    case WebAuthn.authenticate(params, challenge) do
      {:ok, %{user: %{id: ^user_id}}} ->
        conn
        |> UserAuth.mark_reauth(:passkey)
        |> json(%{ok: true})

      other ->
        Logger.info("Passkey re-auth refused: #{inspect(other)}")
        json_error(conn, :unauthorized, @passkey_denied)
    end
  end

  # --- Passkeys --------------------------------------------------------------

  def registration_challenge(conn, _params) do
    {challenge, payload} = WebAuthn.registration_challenge(conn.assigns.current_user)

    conn
    |> WebAuthnSession.put(@registration_key, challenge)
    |> json(payload)
  end

  def create_passkey(conn, params) do
    case WebAuthnSession.take(conn, @registration_key) do
      {:ok, challenge, conn} ->
        register_passkey(conn, params, challenge)

      {:error, conn} ->
        json_error(conn, :unprocessable_entity, "That registration expired. Try again.")
    end
  end

  defp register_passkey(conn, params, challenge) do
    user = conn.assigns.current_user

    case WebAuthn.register(user, params, challenge) do
      {:ok, passkey} ->
        Logger.warning("Passkey #{passkey.nickname} registered for #{user.username}")
        json(conn, %{ok: true})

      {:error, :already_registered} ->
        json_error(conn, :unprocessable_entity, "That security key is already registered.")

      {:error, reason} ->
        Logger.info("Passkey registration refused: #{inspect(reason)}")
        json_error(conn, :unprocessable_entity, "That passkey could not be registered.")
    end
  end

  def delete_passkey(conn, %{"id" => id}) do
    user = conn.assigns.current_user

    # `Passkeys.delete/2` scopes by the owning user, so an id lifted from
    # somebody else's page is simply not found.
    case Passkeys.delete(user, id) do
      :ok ->
        Logger.warning("Passkey removed for #{user.username}")

        conn
        |> put_flash(:info, "Passkey removed.")
        |> redirect(to: ~p"/settings/security")

      {:error, :not_found} ->
        conn
        |> put_flash(:error, "No such passkey on this account.")
        |> redirect(to: ~p"/settings/security")
    end
  end

  # --- TOTP ------------------------------------------------------------------

  def start_totp(conn, _params) do
    {:ok, %{uri: uri}} = Totp.start_enrolment(conn.assigns.current_user)

    render_page(conn, totp_uri: uri)
  end

  def confirm_totp(conn, %{"code" => code}) do
    user = conn.assigns.current_user

    case Totp.confirm(user, code) do
      :ok ->
        Logger.warning("TOTP confirmed for #{user.username}")

        conn
        |> put_flash(:info, "Authenticator app confirmed.")
        |> redirect(to: ~p"/settings/security")

      {:error, _reason} ->
        render_page(conn, error: "That code did not match. Check the clock on the device.")
    end
  end

  def delete_totp(conn, _params) do
    user = conn.assigns.current_user
    :ok = Totp.disable(user)
    Logger.warning("TOTP removed for #{user.username}")

    conn
    |> put_flash(:info, "Authenticator app removed.")
    |> redirect(to: ~p"/settings/security")
  end

  # --- Recovery codes --------------------------------------------------------

  def regenerate_recovery_codes(conn, _params) do
    user = conn.assigns.current_user
    {:ok, codes} = RecoveryCodes.generate(user)
    Logger.warning("Recovery codes regenerated for #{user.username}")

    # Rendered straight into this one response: never stored, never put in the
    # session, never carried across a redirect. See the module doc.
    render_page(conn, new_recovery_codes: codes)
  end

  # --- The step-up gate ------------------------------------------------------

  defp require_fresh_reauth(conn, _opts) do
    user = conn.assigns.current_user

    if Mfa.reauth_fresh?(user, UserAuth.reauth_method(conn), UserAuth.reauth_at(conn)) do
      conn
    else
      conn |> refuse(reauth_message(user)) |> halt()
    end
  end

  defp refuse(conn, message) do
    if conn.private[:phoenix_action] in @json_actions do
      json_error(conn, :forbidden, message)
    else
      conn
      |> put_flash(:error, message)
      |> redirect(to: ~p"/settings/security")
    end
  end

  @no_longer_the_password "Your password no longer authorises changes here."

  defp reauth_message(user) do
    case Mfa.accepted_reauth_methods(user) do
      [:password] ->
        "Confirm your password first."

      [:passkey, :recovery_code] ->
        "Confirm with your passkey or a recovery code first. #{@no_longer_the_password}"

      [:totp, :recovery_code] ->
        "Confirm with a code from your authenticator app, or a recovery code, first. " <>
          @no_longer_the_password
    end
  end

  defp parse_method("password"), do: :password
  defp parse_method("totp"), do: :totp
  defp parse_method("recovery_code"), do: :recovery_code
  defp parse_method(_other), do: :unknown

  defp proven?(user, :password, credential) when is_binary(credential) do
    match?({:ok, _user}, Portal.Accounts.authenticate_user(user.username, credential))
  end

  defp proven?(user, :totp, credential) when is_binary(credential) do
    Totp.verify(user, credential) == :ok
  end

  defp proven?(user, :recovery_code, credential) when is_binary(credential) do
    RecoveryCodes.consume(user, credential) == :ok
  end

  defp proven?(_user, _method, _credential), do: false

  defp json_error(conn, status, message) do
    conn |> put_status(status) |> json(%{error: message})
  end

  defp window_minutes, do: div(Mfa.reauth_window_seconds(), 60)

  defp render_page(conn, extra \\ []) do
    user = conn.assigns.current_user
    accepted = Mfa.accepted_reauth_methods(user)

    conn =
      case Keyword.fetch(extra, :error) do
        {:ok, message} -> put_flash(conn, :error, message)
        :error -> conn
      end

    render(conn, :show,
      page_title: "Security",
      current_user: user,
      passkeys: Passkeys.list_for_user(user),
      totp_confirmed: Totp.confirmed?(user),
      recovery_remaining: RecoveryCodes.remaining(user),
      recovery_low: RecoveryCodes.low?(user),
      enrolled: Mfa.enrolled?(user),
      admin_satisfied: Mfa.admin_satisfied?(user),
      accepted_methods: accepted,
      reauth_fresh:
        Mfa.reauth_fresh?(user, UserAuth.reauth_method(conn), UserAuth.reauth_at(conn)),
      window_minutes: window_minutes(),
      totp_uri: Keyword.get(extra, :totp_uri),
      new_recovery_codes: Keyword.get(extra, :new_recovery_codes)
    )
  end
end
